AWSTemplateFormatVersion: 2010-09-09
Description: Should I Wear A Jacket Service
Transform:
  - AWS::Serverless-2016-10-31

Parameters:
  OpenWeatherBaseUrl:
    Type: String
  FaunaDBSecretKey:
    Type: String
    NoEcho: true

Resources:
  FaunaConnection:
    Type: AWS::Events::Connection
    Properties:
      Name: 'fauna-connection-2'
      AuthorizationType: API_KEY
      AuthParameters:
        ApiKeyAuthParameters:
          ApiKeyName: Authorization
          ApiKeyValue: !Ref FaunaDBSecretKey
        InvocationHttpParameters:
          QueryStringParameters:
            - IsValueSecret: true
              Key: appid
              Value: !Ref FaunaDBSecretKey

  computeResult:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs20.x
      CodeUri: result/
      Description: A Lambda function to compute the result based on weather data.
      Architectures:
        - x86_64
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /compute
            Method: post
  
  ShouldIWearAJacketStateMachine:
    Type: AWS::Serverless::StateMachine
    Properties:
      Type: STANDARD
      DefinitionUri: ./workflows/query-global.asl.json
      DefinitionSubstitutions:
        OpenWeatherBaseUrl: !Ref OpenWeatherBaseUrl
        FaunaConnectionArn: !GetAtt FaunaConnection.Arn
        ComputeResultFunctionArn: !GetAtt computeResult.Arn
      Policies:
        - Version: 2012-10-17
          Statement:
            - Effect: Allow
              Action:
                - secretsmanager:DescribeSecret
                - secretsmanager:GetSecretValue
              Resource: !GetAtt FaunaConnection.SecretArn
            - Effect: Allow
              Action:
                - events:RetrieveConnectionCredentials
              Resource: !GetAtt FaunaConnection.Arn
            - Effect: Allow
              Action:
                - states:InvokeHTTPEndpoint
              Resource: "*"
              Condition:
                StringEquals:
                  states:HTTPMethod: POST
                StringLike:
                  states:HTTPEndpoint: !Ref OpenWeatherBaseUrl
            - Effect: Allow
              Action:
                - lambda:InvokeFunction
              Resource: !GetAtt computeResult.Arn