AWSTemplateFormatVersion: 2010-09-09
Description: Should I Wear A Jacket Service
Transform:
  - AWS::Serverless-2016-10-31

Parameters:
  OpenWeatherBaseUrl:
    Type: String
  OpenWeatherAPIKey:
    Type: String
    NoEcho: true

Resources:
  OpenWeatherConnection:
    Type: AWS::Events::Connection
    Properties:
      Name: 'fauna-connection'
      AuthorizationType: API_KEY
      AuthParameters:
        ApiKeyAuthParameters:
          ApiKeyName: Authorization
          ApiKeyValue: !Ref OpenWeatherAPIKey
        InvocationHttpParameters:
          QueryStringParameters:
            - IsValueSecret: true
              Key: appid
              Value: !Ref OpenWeatherAPIKey

  ShouldIWearAJacketStateMachine:
    Type: AWS::Serverless::StateMachine
    Properties:
      Type: STANDARD
      DefinitionUri: ./workflows/query-global.asl.json
      DefinitionSubstitutions:
        OpenWeatherBaseUrl: !Ref OpenWeatherBaseUrl
        OpenWeatherConnectionArn: !GetAtt OpenWeatherConnection.Arn
      Policies:
        - Version: 2012-10-17
          Statement:
            - Effect: Allow
              Action:
                - secretsmanager:DescribeSecret
                - secretsmanager:GetSecretValue
              Resource: !GetAtt OpenWeatherConnection.SecretArn
            - Effect: Allow
              Action:
                - events:RetrieveConnectionCredentials
              Resource: !GetAtt OpenWeatherConnection.Arn
            - Effect: Allow
              Action:
                - states:InvokeHTTPEndpoint
              Resource: "*"
              Condition:
                StringEquals:
                  states:HTTPMethod: POST
                StringLike:
                  states:HTTPEndpoint: !Ref OpenWeatherBaseUrl